### ISSUE TITLE
Clean up experiments 

### ISSUE THREAD

**Issue by lopollar** [saeyslab/napari-sparrow#116]
Currently, experiments is a collection of notebooks, where no one knowns which one to use, or which ones are updated. 
I would create multiple notebooks at the moment:
- RESOLVE Liver
- vizgen liver: on both segmented together: vizgen polyT tutorial  
- StereoSeq brain
- Xenium (still quite some work)
- example on how to use hydra 
- Notebook on visualization in napari: adapt annotate_veins 
- Notebook on matching cells across data objects? comparisonPolyTDAPI
- Notebook on image feature extraction? feature_extraction

**Comment by ArneDefauw** [comment]
see https://sparrow-pipeline.readthedocs.io/en/latest/tutorials/index.html. Please reopen if these other tutorials are still a priority
