### ISSUE TITLE
Testing of output for the different plots

### ISSUE THREAD

**Issue by SilverViking** [saeyslab/napari-sparrow#118]
We can get some inspiration from [squidpy ](https://github.com/scverse/squidpy) for testing the output of the different plots that napari-sparrow generates:

- "Ground truth" matplotlib output is stored as images in the [tests folder](https://github.com/scverse/squidpy/tree/642b257a350e4db451882bc8275b8b1d0c38a468/tests/_images).
- A [PlotTester ](https://github.com/scverse/squidpy/blob/642b257a350e4db451882bc8275b8b1d0c38a468/tests/conftest.py) class   saves a matplotlib plotting context to an image file and then compares this image against the ground truth image.
- Plot output images are compared using matplotlib's [compare_images](https://matplotlib.org/stable/api/testing_api.html#matplotlib.testing.compare.compare_images) function.

**Comment by ArneDefauw** [comment]
There are unit tests for plotting functions of sparrow here, https://github.com/saeyslab/napari-sparrow/tree/main/src/sparrow/_tests/test_image. Due to non deterministic nature of most plots (os, python version, library versions),will close this issue for now.
