### ISSUE TITLE
Calculate average pixel brightness per segmented object

### ISSUE THREAD

**Issue by lopollar** [saeyslab/napari-sparrow#130]
I think there is a high negative correlation between the brightness of a cell and the amount of transcripts picked up in that cell. 
Of course we will have to correct for celltypes here, but still. 
So I would love to have a function that can calculate the brightness of a cell by using the masks. 
I am trying some code and it works, but is insanely slow. 

So if anyone has an idea, please shoot!

**Comment by ArneDefauw** [comment]
should be supported by https://github.com/saeyslab/napari-sparrow/blob/1891fbdc803038b45b156ef5564a1d1982ed4017/src/sparrow/table/_allocation_intensity.py#L23, please reopen if some features would be missing
