### ISSUE TITLE
labels to shapes function

### ISSUE THREAD

**Issue by julienmortier** [saeyslab/napari-sparrow#184]
I often find myself needing to convert a shapes layer to a labels layer, but currently there is no function in sparrow that does this (not that I can find anyway). I have currently needed it in of 2 flavors:

1) Converting the cell segmentation shapes to a labels mask where the cell indexes are preserved.
2) Converting a region annotation to a binary mask

Based on some suggestions from Arne, I currently use the functions below, but it would be more streamlined if a more general single function would be implemented in sparrow. However, I am not exactly sure how to properly do this myself within the sparrow codebase:) Also, I wonder whether these types of functions are something that would fit better within the spatialdata package itself?

```
import rasterio.features
from affine import Affine

def create_labels_from_shapes(sdata, shapes_layer: str, out_shape: list, output_layer: str):
    
    transform = Affine.translation(0, 0)
    
    masks = rasterio.features.rasterize(
        zip(
            sdata[shapes_layer].geometry,
            sdata[shapes_layer].index.values.astype(float),
        ),
        out_shape=out_shape,
        dtype="uint32",
        fill=0,
        transform=transform
    )

    sdata = sp.im._add_label_layer(sdata, arr=masks, chunks=1024, output_layer=output_layer)

    return sdata
```

```
import rasterio.features
from affine import Affine

def create_binary_mask_from_shapes(sdata, shapes_layer: str, out_shape: list, output_layer: str):
    
    transform = Affine.translation(0, 0)
    
    masks = rasterio.features.rasterize(
        sdata[shapes_layer].geometry,
        out_shape=out_shape,
        dtype="uint8",
        fill=0,
        transform=transform,
        default_value=1,
    )

    sdata = sp.im._add_label_layer(sdata, arr=masks, chunks=1024, output_layer=output_layer)

    return sdata
```

**Comment by ArneDefauw** [comment]
implemented here https://github.com/saeyslab/napari-sparrow/blob/1891fbdc803038b45b156ef5564a1d1982ed4017/src/sparrow/image/_rasterize.py#L25 .
