### ISSUE TITLE
Bug in allocate_intensity, does segmentation

### ISSUE THREAD

**Issue by berombau** [saeyslab/napari-sparrow#185]
@ArneDefauw I have a weird bug where `allocate_intensity` is very slow. When looking at the Dask dashboard, it seems to not use the segmentation_mask already in the SpatialData object from the `segment` step before, but some reference still to the segmentation step that created it. So every chunk holds up the line in the Dask graph waiting for cellpose to execute on it again, instead of using the mask.

```python
import sparrow as sp
import spatialdata as sd
from dask.distributed import Client, LocalCluster

cluster = LocalCluster(host="localhost")
client = Client(cluster)
```

My image, but maybe sd.datasets.blobs will give the same error
```
SpatialData object with:
└── Images
      └── 'raw_image': SpatialImage[cyx] (43, 830, 830)
with coordinate systems:
▸ 'global', with elements:
        raw_image (Images)
```
```python
# run in 17 seconds
sp.im.segment(
    sdata,
    img_layer="raw_image",
    diameter=30,
    cellprob_threshold=-4,
    flow_threshold=0.9,
    model_type="nuclei",
    # output_labels_layer="segmentation_mask",
    do_3D=False,
    channels=[1, 0],
    # overwrite=True,
)

# runs for 10 min on 1.000 x 1.000
sdata = sp.tb.allocate_intensity(sdata, img_layer="raw_image", labels_layer="segmentation_mask", chunks=100)
```

It's hard to debug, I can try to create a better issue next week. It could also be that the backed zarr or some rechunking messes up the graph: `sdata.images[el_name].data = sdata.images[el_name].data.rechunk()`

**Comment by ArneDefauw** [comment]
Backed spatialdata objects should be read back from the zarr store. I think this is desired behaviour of spatialdata for now. Inplace update of spatialdata objects should be covered in spatialdata library, not in sparrow. Closing for now.
