### ISSUE TITLE
Caching the pipeline

### ISSUE THREAD

**Issue by berombau** [saeyslab/napari-sparrow#47]
We want to cache certain parts of the pipeline. This way, we can develop faster and users can tweak downstream steps of the pipeline without rerunning long upstream steps.

We can solve this in 3 ways:

1. serializing an intermediate step and manually supporting this as input data
e.g. the segmentation mask. We support giving a segmentation mask as input data (because it already exists, or other tools are preferred). This is extra functionality, but supporting this for each intermediate step is burdensome.

2. Using Dask Cache (https://docs.dask.org/en/stable/caching.html). Probably won't work for large datasets and does not give intelligent cache reuse.

3. Using graphchain (https://github.com/radix-ai/graphchain). Support intelligent cache reuse, but unknown performance on our kind of imaging data.

We should probably research step 3 and support step 1 use cases when asked for by users.

**Comment by ArneDefauw** [comment]
Closing this issue as it has become stale.
