### ISSUE TITLE
Use progress bar

### ISSUE THREAD

**Issue by berombau** [saeyslab/napari-sparrow#75]
The status of really long actions can be viewable for the user in napari using a [progress bar](https://napari.org/stable/api/napari.utils.progress.html). See for example https://forum.image.sc/t/progress-bar-for-cellpose-plugin-in-napari/55593.

We can implement this for long-running jobs, but:

- the user should preferably use the Hydra job runner 
- if implemented in Dask, there could be automatic support for a progress bar [later on](https://github.com/napari/napari/issues/3418) (this depends on async slicing)
- if there is async slicing, we can probably have more immediate interactivity and then the user has less need for progress bars

We can add this for really long-running segmentation step manually like in the example, but where this is not the priority we can wait for more Dask integration to support progress on all the other functions.

**Comment by ArneDefauw** [comment]
Closing this issue as it has become stale
