### ISSUE TITLE
Define dependencies for Python package

### ISSUE THREAD

**Issue by berombau** [saeyslab/napari-sparrow#76]
If we want to submit our package to PyPi, we need to define the requirements in a requirements.txt or in [pyproject.toml](). 

Right now we only have 1 conda environment.yaml with everything: build-dependencies, cudatools, direct dependencies, jupyterlab, dev dependencies, test dependencies...

Conda-based plugins in napari are however [supported](https://forum.image.sc/t/install-napari-plugin-with-conda-cudatoolkit-dependency/70385) and is also the future direction of napari packaging. But we want to support both PyPi and conda for now.

- [ ] define minimal dependencies to run napari plugin
- [ ] ensure `pip install -e .` still works
- [ ] also install Hydra and CLI
- [ ] document GPU installation with PyTorch
- [ ] support [testing] (CI tooling, pytest...) and [dev] (testing + jupyterlab...)
- [ ] edit GitHub Actions to build and publish to PyPI with Twine

**Comment by ArneDefauw** [comment]
Fixed on main. Should be ready to publish to PyPi
