### ISSUE TITLE
Plot all masks types in napari

### ISSUE THREAD

**Issue by berombau** [saeyslab/napari-sparrow#95]
Currently, a lot of different cell annotation masks are generated and visualized in the notebooks using matplotlib or [sq.pl.spatial_segment](https://squidpy.readthedocs.io/en/stable/auto_examples/image/compute_show.html):

1. instance mask from the cellpose segmentation step (every cell a unique ID)
  - from which we calculate GeoPandas polygons, do some filtering and can again rasterize to a filtered instance mask
2. filtered instance mask (every cell a unique ID)
3. filtered semantic mask annotated by cell cluster after allocation step and clustering (every cell a cluster ID)
4. filtered semantic mask annotated by a cell type after annotation step (every cell a cell type annotation)

The colors for instance masks and cell clusters should be random using the default colors.
The colors for the cell annotation should come from an upfront defined colormap, so each cell type has a stable color.

napari-spatialdata currently supports visualization of a categorical observation for each cell, but using a colored Points layer.

A napari Labels layer should be created for each mask type and with the correct [face_color](https://napari.org/stable/api/napari.layers.Labels.html):
- [x] instance mask
- [ ] filtered instance mask
- [ ] filtered semantic cluster mask
- [ ] filtered semantic annotation mask

**Comment by ArneDefauw** [comment]
Closing this issue as it has become stale. Plugin supports most of the features described here.
