### ISSUE TITLE
Add Baysor for cell segmentation

### ISSUE THREAD

**Issue by rseurinc** [saeyslab/napari-sparrow#96]
A combination of CellPose and Baysor might optimize the segmentation further. Data sets with cell surface markers could help in evaluating the added value of using CellPose alone vs CellPose as a prior for Baysor.

**Comment by SilverViking** [comment]
@ArneDefauw Meanwhile Baysor is supported in Sparrow, no? This issue can be closed as completed?
(https://sparrow-pipeline.readthedocs.io/en/latest/generated/sparrow.im.segment_points.html)

**Comment by lopollar** [comment]
yes!
