### ISSUE TITLE
Adapt code to Xenium data

### ISSUE THREAD

**Issue by lopollar** [saeyslab/napari-sparrow#97]
In order to add different other types of data, adaptations need to be made on names of functions/parameters/....

Extra functions need to be written for:

- putting the csv into the correct format
- Working with a Dask DataFrame instead of a pandas (always or only when needed?)
- marker gene lists need to be selected 
- looking into nucleus size normalization: an error there 
- parallelization of the segmentation
- adapt the mask to float32

**Comment by ArneDefauw** [comment]
closed by https://github.com/saeyslab/napari-sparrow/pull/205
